/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SigninImport } from './routes/signin'
import { Route as WorkspaceImport } from './routes/_workspace'
import { Route as IndexImport } from './routes/index'
import { Route as WorkspaceWorkspaceWorkspaceIdImport } from './routes/_workspace/workspace/$workspaceId'

// Create/Update Routes

const SigninRoute = SigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const WorkspaceRoute = WorkspaceImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WorkspaceWorkspaceWorkspaceIdRoute =
  WorkspaceWorkspaceWorkspaceIdImport.update({
    id: '/workspace/$workspaceId',
    path: '/workspace/$workspaceId',
    getParentRoute: () => WorkspaceRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WorkspaceImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
    '/_workspace/workspace/$workspaceId': {
      id: '/_workspace/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof WorkspaceWorkspaceWorkspaceIdImport
      parentRoute: typeof WorkspaceImport
    }
  }
}

// Create and export the route tree

interface WorkspaceRouteChildren {
  WorkspaceWorkspaceWorkspaceIdRoute: typeof WorkspaceWorkspaceWorkspaceIdRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceWorkspaceWorkspaceIdRoute: WorkspaceWorkspaceWorkspaceIdRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof WorkspaceRouteWithChildren
  '/signin': typeof SigninRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceWorkspaceIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof WorkspaceRouteWithChildren
  '/signin': typeof SigninRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceWorkspaceIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/signin': typeof SigninRoute
  '/_workspace/workspace/$workspaceId': typeof WorkspaceWorkspaceWorkspaceIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/signin' | '/workspace/$workspaceId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/signin' | '/workspace/$workspaceId'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/signin'
    | '/_workspace/workspace/$workspaceId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  SigninRoute: typeof SigninRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  SigninRoute: SigninRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_workspace",
        "/signin"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_workspace": {
      "filePath": "_workspace.tsx",
      "children": [
        "/_workspace/workspace/$workspaceId"
      ]
    },
    "/signin": {
      "filePath": "signin.tsx"
    },
    "/_workspace/workspace/$workspaceId": {
      "filePath": "_workspace/workspace/$workspaceId.tsx",
      "parent": "/_workspace"
    }
  }
}
ROUTE_MANIFEST_END */
